DEVICE_PATH := device/oukitel/WP19_Pro

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic

# Platform
TARGET_BOARD_PLATFORM := mt6789
TARGET_BOOTLOADER_BOARD_NAME := WP19_Pro

# Recovery / OrangeFox
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery.fstab

# A/B device
AB_OTA_UPDATER := true
ENABLE_AB := true

# Partitions (dynamic)
BOARD_SUPER_PARTITION_SIZE := 9126805504
BOARD_SUPER_PARTITION_GROUPS := main
BOARD_MAIN_SIZE := 9126805504

BOARD_BUILD_SYSTEM_ROOT_IMAGE := false

# Kernel (we use vendor_boot recovery style)
TARGET_NO_KERNEL := true
BOARD_HAS_LARGE_FILESYSTEM := true

# AVB
BOARD_AVB_ENABLE := true

# Recovery flags
TW_THEME := portrait_hdpi
TW_INCLUDE_CRYPTO := true
TW_USE_TOOLBOX := true
TW_INCLUDE_NTFS_3G := true

# MTK specifics
BOARD_HAS_MTK_HARDWARE := true
MTK_HARDWARE := true
