name: Custom TWRP Builder
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize Build Environment
        run: |
          sudo apt update && sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          sudo ln -sf ~/bin/repo /usr/bin/repo

      - name: Sync TWRP Source
        run: |
          mkdir android-recovery
          cd android-recovery
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
          repo sync -j$(nproc --all)

      - name: Clone Device Tree
        run: |
          # Replace this with your own repo URL
          git clone https://github.com/Isadowski09/device-oukitel-WP19_Pro- android-recovery/device/oukitel/WP19_Pro

      - name: Build
        run: |
          cd android-recovery
          source build/envsetup.sh
          lunch twrp_WP19_Pro-eng
          mka vendorbootimage -j$(nproc --all)

      - name: Upload Artifact
        uses: softprops/action-gh-release@v2
        with:
          files: android-recovery/out/target/product/WP19_Pro/vendor_boot.img
          tag_name: build-${{ github.run_id }}
          token: ${{ secrets.GITHUB_TOKEN }}
